packages:
  - name: notion-cms
    actions:
      - name: rebuild
        main: ""
        runtime: "nodejs:18"
        web: true
        environment:
          APP_ID: "${APP_ID}"
          API_KEY: "${API_KEY}"
          REBUILD_TOKEN: "${REBUILD_TOKEN}"
