version: '3.8'
services:
  portfolio:
    build:
      context: ../infrastructure/app
      target: dev
    volumes:
      - ..:/app
    ports:
      - '8080:8080'
    command: /bin/sh -c "while sleep 1000; do :; done"
